/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mantegral.Headtrack_UDP;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int addressEditText=0x7f060006;
        public static final int button=0x7f060008;
        public static final int kalman=0x7f060004;
        public static final int mean=0x7f060003;
        public static final int portEditText=0x7f060007;
        public static final int rX=0x7f060009;
        public static final int rY=0x7f06000a;
        public static final int rZ=0x7f06000b;
        public static final int text=0x7f060005;
        public static final int text2=0x7f060000;
        public static final int time=0x7f060001;
        public static final int timeLabel=0x7f060002;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class style {
        public static final int AppTheme=0x7f050000;
    }
}
